server:
  port: 8001

# 下面是Mybatis的整合
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.isea.learn.entities    # 所有Entity别名类所在包，告诉mybatis，只要是这个包下面的，统统都是一个个实体类
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

# spring的整合
spring:
  application:                                             # 对于微服务最重要的名字，
    name: microservicecloud-dept                            # 对外暴露的微服务的名字，在erueka中会全部修改成大写的。
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
#    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
    username: root
    password: hailong1996
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: microservicecloud-dept8001   #自定义服务名称信息，microservicecloud-dept8001是服务名称，一个微服务，可以对应多个instance，这样就可以实现负载
                                               # 对应着erueka页面中的up位置，我们更希望该位置在鼠标覆盖的时候是ip+port的形式来展现
    prefer-ip-address: true     #访问路径可以显示IP地址，比如之前显示的是localhost，但是现在可以显示localhost对应的主机的IP地址

info:
  app.name: isea-microservicecloud
  company.name: www.isea.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$