server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

# 将原来的微服务名称修改为mydept，更加安全。
zuul:
#  ignored-services: microservicecloud-dept  # 将原来的带有微服务名称的地址封了，只能使用别名的方式来访问
  prefix: /isea  # 在所有的服务前面都需要添加/isea  [zuul代理的地址 + /isea + 微服务别名 + restful风格的地址]
  ignored-services: "*"  # 将所有真实的微服务的名字都禁掉
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**


info:
  app.name: isea-microservicecloud
  company.name: www.isea.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$